version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: .docker/app.dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .docker/nginx-conf:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33066:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app

  db-test:
    image: mysql:8.0
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${TEST_DB_DATABASE}
        MYSQL_USER: ${TEST_DB_USERNAME}
        MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - mysql-data-test:/var/lib/mysql
    networks:
      - app

volumes:
  mysql-data:
  mysql-data-test:

networks:
  app:
